      <!-- banner -->
      <div class="panel panel-dark-blue trailer-2">
        <div class="grid-container">
          <div class="column-24">
            <a href="index.html"><h1 class="sub-nav-title  text-white">Arkanstats</h1></a>
			<nav class="sub-nav-list" role="navigation" aria-labelledby="subnav">
			  <a href="Economy.html" class="sub-nav-link  is-active ">Economy</a>
			  <a href="Infrastructure.html" class="sub-nav-link ">Infrastructure</a>
			  <a href="Education.html" class="sub-nav-link ">Education and Human Capital</a>
			  <a href="Quality.html" class="sub-nav-link ">Quality of Life and Place</a>
			  <a href="Demographics.html" class="sub-nav-link ">Demographics</a>
			</nav>         
		  </div>
        </div>
      </div>

      <!-- main-content -->
      <div class="grid-container">

        <!-- side navigation -->
        <div class="column-4">
			<aside class="side-nav" aria-role="complementary">
            <h4 class="side-nav-title text-blue">Economy</h4>			
				<aside class="js-accordion accordion">
				  <div class="accordion-section"  id="a1">
					<h4 class="accordion-title">
					  <span class="accordion-icon">
						<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 32 32" class="svg-icon"><path d="M28 9v5L16 26 4 14V9l12 12L28 9z"/></svg>
					  </span>
					  Output
					</h4>
					<div class="accordion-content">
						<nav role="navigation" aria-labelledby="sidenav">
						  <a href="#" class="side-nav-link padding-left-2  is-active">GDP</a>
						  <!--a href="#" class="side-nav-link padding-left-2  is-active">By metro </a-->
						</nav>				  
					</div>
				  </div>
				  <div class="accordion-section">
					<h4 class="accordion-title">
					  <span class="accordion-icon">
						<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 32 32" class="svg-icon"><path d="M28 9v5L16 26 4 14V9l12 12L28 9z"/></svg>
					  </span>
					  Income
					</h4>
					<div class="accordion-content">
						<nav role="navigation" aria-labelledby="sidenav">
						  <a href="EconomyIncomePersonal.html" class="side-nav-link padding-left-2">Personal</a>
						  <a href="#" class="side-nav-link padding-left-2">Per capita</a>
						</nav>				  
					</div>
				  </div>
				  <div class="accordion-section">
					<h4 class="accordion-title">
					  <span class="accordion-icon">
						<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 32 32" class="svg-icon"><path d="M28 9v5L16 26 4 14V9l12 12L28 9z"/></svg>
					  </span>
					  Employment
					</h4>
					<div class="accordion-content">
						<nav role="navigation" aria-labelledby="sidenav">
						  <a href="#" class="side-nav-link padding-left-2">Link 1</a>
						  <a href="#" class="side-nav-link padding-left-2">Link 2</a>
						</nav>				  
					</div>
				  </div>
				  <div class="accordion-section">
					<h4 class="accordion-title">
					  <span class="accordion-icon">
						<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 32 32" class="svg-icon"><path d="M28 9v5L16 26 4 14V9l12 12L28 9z"/></svg>
					  </span>
					  Spending
					</h4>
					<div class="accordion-content">
						<nav role="navigation" aria-labelledby="sidenav">
						  <a href="#" class="side-nav-link padding-left-2">PCE</a>
						  <a href="#" class="side-nav-link padding-left-2">Arkansas Tax Sales</a>
						</nav>				  
					</div>
				  </div>
				</aside>			
				<!--nav role="navigation" aria-labelledby="sidenav">
				  <a href="#" class="side-nav-link">Population Components</a>
				  <a href="#" class="side-nav-link">Population Characteristics</a>
				  <a href="#" class="side-nav-link">Projections</a>
				</nav-->
			  </aside>
			 </aside>	  
		</div>
        <!-- main content list -->